# Jupyter Book settings

title: Python exos
author: Thierry Parmentelat
logo: media/logo-python.svg

only_build_toc_files: true

exclude_patterns:
  - "**/.teacher/*"

execute:
  execute_notebooks: cache
  exclude_patterns:
    - "**/*-corrige*"
    - "**/.teacher/*"

parse:
  myst_enable_extensions:
    - html_image    # for raw <img> tags in markdown
    - dollarmath    # for mathjax
    - strikethrough

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    html_theme_options:
      repository_url: https://github.com/flotpython/slides
      repository_branch: main
      path_to_docs: notebooks
      use_issues_button: yes
      use_repository_button: yes
      use_download_button: yes
      home_page_in_toc: false
      toc_title: "Dans cette section:"

    html_favicon: ../media/logo-p24-favicon.svg
    html_show_copyright: false
    # not quite convincing but...
    html_extra_path:
      - media
    # required as of 2024 May to get %matplotlib ipympl
    # to show up (at all, not even interactive) in the book output
    nb_ipywidgets_js:
        # Load RequireJS, used by the IPywidgets for dependency management
        "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js":
            "integrity": "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
            "crossorigin": "anonymous"
        # Load IPywidgets bundle for embedding.
        "https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@*/dist/embed-amd.js":
            "data-jupyter-widgets-cdn": "https://cdn.jsdelivr.net/npm/"
            "crossorigin": "anonymous"
